runtime: nodejs18

instance_class: F2

automatic_scaling:
  target_cpu_utilization: 0.65

env_variables:
  MYSQL_USER: root
  MYSQL_PASSWORD: root4995
  MYSQL_DATABASE: feedpicker_db
  MYSQL_HOST: /cloudsql/ch2-ps518:asia-southeast2:ch2-ps518